apiVersion: v1
entries:
  go-app-chart:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-12-13T19:37:16.372513+01:00"
    description: A Helm chart for 3 tier Go App (UI, Backend, Database)
    digest: 0b15e264b3bfe38ddd16b8aa717b254b98b575e63f130875c266e80f63bba415
    maintainers:
    - email: fiduh987@gmail.com
      name: aceklnoudnative
    name: go-app-chart
    type: application
    urls:
    - https://fiduh.github.io/k8s/eksctl/go-app-chart/charts/go-app-chart-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-13T19:37:16.36957+01:00"
