apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: go-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Use AWS ALB
    ingressClassName: alb
spec:
  rules:
    - http:
        paths:
          - path: /api/record
            pathType: Prefix
            backend:
              service:
                name: backend-service.go-backend
                port:
                  number: 80
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service.go-ui
                port:
                  number: 80
