apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-{{ .Values.app.backend.name }}
data:
  {{- with .Values.app.backend.config }}
  MONGO_URI: {{ .uri }}
  PORT: {{ .port }}
  {{- end }}


