apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.db.name }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.app.db }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1002
        runAsGroup: 3002
        fsGroup: 2002
        runAsNonRoot: true
      containers:
        - name: {{ .name }}
          image: {{ .image.repository }}:{{ .image.tag }}
          # args: ["--unixSocketPrefix", "/data/db/tmp"]
          ports:
            - containerPort: {{ .port }}
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
            - name: tmp-storage
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: tmp-storage
          emptyDir: {} # Writable temporary storage for MongoDB operations
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.db.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.app.db}}
  selector:
    app: {{ .name }}
  ports:
    - protocol: {{ .service.protocol }}
      port: {{ .service.port }}
      targetPort: {{ .service.targetPort }}
  type: {{ .service.type }}
  {{- end }}
